name: Deploy WordsJar Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
      - 'docs/**'
      - '.gitignore'

env:
  WORK_DIR: ${{ vars.WORK_DIR }}

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: copy ssh private key to file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/key.pem
          chmod 600 ~/key.pem

      - name: Add remote host to known_hosts
        run: |
          ssh-keyscan -H -p ${{ vars.SSH_PORT }} ${{ vars.SSH_ADDR }} >> ~/.ssh/known_hosts

      - name: Create work dir and checkout code
        run: |
          ssh -i ~/key.pem -o StrictHostKeyChecking=no -p ${{ vars.SSH_PORT }} ${{ vars.SSH_USER }}@${{ vars.SSH_ADDR }} "
            set -e
            mkdir -p ${{ env.WORK_DIR }}
            cd ${{ env.WORK_DIR }}
            git init
            git remote add origin https://github.com/${{ github.repository }}.git 2>/dev/null || true
            git fetch origin ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}
            git sparse-checkout init --cone
            git sparse-checkout set backend
            git checkout ${{ github.ref_name }}
          "

      - name: Restart systemd service
        run: ssh -i ~/key.pem -o StrictHostKeyChecking=no -p ${{ vars.SSH_PORT }} ${{ vars.SSH_USER }}@${{ vars.SSH_ADDR }} "systemctl restart ${{ vars.SYSTEMD_SERVICE_NAME }}"