
class NotFound(Exception): ...


class InternalError(Exception): ...


class AuthError(Exception): ...


class AlreadyExistsError(Exception): ...


class ExpiredTokenError(Exception): ...